ALTER TABLE services ADD COLUMN crash_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN circuit_open INTEGER NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN last_crashed_at INTEGER;
